apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
  namespace: ecommerce
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: postgres-order }
  template:
    metadata:
      labels: { app: postgres-order }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports: [{ containerPort: 5432 }]
          env:
            - { name: POSTGRES_USER, value: "orderservice" }
            - { name: POSTGRES_DB, value: "orderdb" }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: ecommerce-secrets, key: POSTGRES_ORDER_DB_PASSWORD }
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data, subPath: postgres }
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "orderservice"] }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec: { command: ["pg_isready", "-U", "orderservice"] }
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: postgres-order-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  selector: { app: postgres-order }
  ports: [{ port: 5432, targetPort: 5432 }]
